name:                hs-cypher
version:             0.1.0.0
github:              "tim-clifford/hs-cypher"
license:             BSD3
author:              "Tim Clifford"
maintainer:          "tclifford@protonmail.com"
copyright:           "Copyright (c) 2021 Tim Clifford"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tim-clifford/hs-cypher#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hs-cypher-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-cypher

tests:
  hs-cypher-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-cypher
